      - name: Setup Buildozer
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools
          ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin $ANDROID_SDK_ROOT/tools/bin

          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo '[app]
title = My Application
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy==2.1.0,pillow,arabic_reshaper,python-bidi,android
android.api = 33
android.minapi = 21
android.accept_sdk_license = True
android.sdk_path = /opt/android-sdk
orientation = portrait
android.archs = arm64-v8a,armeabi-v7a
android.allow_backup = True

[buildozer]
log_level = 2
warn_on_root = 1' > buildozer.spec
          fi
