name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache .buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-18-jdk \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            python3-pip

          # Set JAVA_HOME to use OpenJDK 18
          sudo update-alternatives --config java
          echo "JAVA_HOME=/usr/lib/jvm/java-18-openjdk-amd64" | sudo tee -a /etc/environment
          source /etc/environment

          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK + AIDL
        env:
          ANDROID_SDK_ROOT: /opt/android-sdk
        run: |
          # Create necessary directories
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          
          # Download the correct command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip

          # Ensure the tools are in the right place (cmdline-tools/latest/)
          mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/

          # Make sure the tools are available in the expected directory
          mv $ANDROID_SDK_ROOT/cmdline-tools /opt/android-sdk/cmdline-tools/latest

          # Accept licenses and install necessary components using sdkmanager
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
          
          # Accept all licenses automatically
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install AIDL if it's not available in build-tools
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2" "platform-tools" "platforms;android-33" "cmdline-tools;latest"

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
