name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: /opt/android-sdk
  ANDROID_NDK_HOME: /opt/android-ndk/25.1.8937393
  BUILDDOZER_ANDROID_ACCEPT_LICENSE: yes

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses5 \
            zlib1g-dev \
            python3-pip \
            python3-dev

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.33 buildozer

      - name: Install Android NDK
        run: |
          sudo mkdir -p /opt/android-ndk
          sudo chown -R $USER:$USER /opt/android-ndk
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d /opt/android-ndk
          mv /opt/android-ndk/android-ndk-r25b /opt/android-ndk/25.1.8937393
          echo "ANDROID_NDK_HOME=/opt/android-ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown -R $USER:$USER $ANDROID_SDK_ROOT
          
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-latest
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools-latest $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Kivy dependencies
        run: |
          pip install kivy==2.1.0 kivymd==1.1.1 pillow arabic_reshaper python-bidi mutagen

      - name: Configure Buildozer
        run: |
          mkdir -p ~/.buildozer
          echo "[buildozer]" > ~/.buildozer/buildozer.spec
          echo "log_level = 1" >> ~/.buildozer/buildozer.spec

      - name: Build with Buildozer
        timeout-minutes: 60
        run: |
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.2
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROIDNDK=$ANDROID_NDK_HOME
          export ANDROIDAPI=33
          
          # Save full log to file
          buildozer --verbose android debug 2>&1 | tee build.log
          
          # Compress logs for artifact
          tar czf logs.tar.gz .buildozer/*.log build.log
          
          # Upload full logs as artifact
          if [ -f "bin/*.apk" ]; then
            echo "Build successful!"
          else
            echo "Build failed! Showing errors:"
            grep -i error build.log | head -n 50
            exit 1
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs.tar.gz