name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # الخطوة 1: استخراج الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد بايثون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # الخطوة 3: تثبيت Java 17 (المطلوبة لـ Android SDK)
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 4: تثبيت التبعيات الأساسية
      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            python3-pip \
            make \
            autoconf \
            automake \
            libtool \
            patchelf \
            libltdl-dev \
            libxml2-dev \
            libxslt-dev

      # الخطوة 5: تثبيت تبعيات بايثون
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install cython==0.29.33 buildozer==1.4.0 virtualenv
          pip install arabic-reshaper python-bidi

      # الخطوة 6: تثبيت Android SDK و NDK
      - name: Install Android tools
        run: |
          # إعداد متغيرات البيئة
          ANDROID_SDK_ROOT="/opt/android-sdk"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

          # إنشاء المجلدات وتغيير الملكية
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown -R $USER:$USER $ANDROID_SDK_ROOT

          # تنزيل وتثبيت أدوات القيادة (الإصدار الأحدث)
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          # إعداد المسار الصحيح
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"

          # قبول الرخص
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

          # تثبيت المكونات الأساسية باستخدام Java 17
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "cmdline-tools;latest"
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

          # إعداد متغيرات NDK
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      # الخطوة 7: التحقق من الأدوات
      - name: Verify tools
        run: |
          echo "=== Java Version ==="
          java -version
          javac -version
          
          echo "=== Android Tools ==="
          sdkmanager --version
          sdkmanager --list --sdk_root=$ANDROID_SDK_ROOT
          adb version

      # الخطوة 8: إعداد Buildozer
      - name: Setup Buildozer
        run: |
          # إنشاء رابط رمزي للتتوافق مع Buildozer
          mkdir -p $ANDROID_SDK_ROOT/tools
          ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin $ANDROID_SDK_ROOT/tools/bin

          # تعديل ملف buildozer.spec
          sed -i "s|^android.ndk_path = .*|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec
          sed -i "s|^android.sdk_path = .*|android.sdk_path = $ANDROID_SDK_ROOT|" buildozer.spec

      # الخطوة 9: البناء باستخدام Buildozer
      - name: Build with Buildozer
        run: |
          # تنزيل python-for-android مسبقاً
          mkdir -p ~/.buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          cd ~/.buildozer/android/platform/python-for-android
          git checkout master
          pip install -e .

          # البناء مع تسجيل كامل
          buildozer -v android debug 2>&1 | tee build.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== Build Failed ==="
            cat build.log
            exit 1
          fi

      # الخطوة 10: رفع الملف الناتج
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
          retention-days: 7
