name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # الخطوة 1: استخراج الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # الخطوة 3: إعداد Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 4: تثبيت التبعيات الأساسية
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            python3-pip \
            make \
            autoconf \
            automake \
            libtool \
            patchelf \
            libltdl-dev \
            libxml2-dev \
            libxslt-dev

      # الخطوة 5: تثبيت تبعيات Python
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install cython==0.29.33 buildozer==1.4.0
          pip install kivy==2.1.0 pillow arabic-reshaper python-bidi

      # الخطوة 6: تثبيت وتكوين Android SDK
      - name: Install Android SDK
        run: |
          ANDROID_SDK_ROOT="/opt/android-sdk"
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown -R $USER:$USER $ANDROID_SDK_ROOT

          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      # الخطوة 7: إعداد Buildozer
      - name: Setup Buildozer environment
        run: |
          # إنشاء رابط رمزي للتتوافق مع Buildozer
          mkdir -p $ANDROID_SDK_ROOT/tools
          ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin $ANDROID_SDK_ROOT/tools/bin

          # إنشاء ملف buildozer.spec إذا لم يكن موجوداً
          if [ ! -f buildozer.spec ]; then
            buildozer init
            # تعديل الملف المبدئي ليتوافق مع احتياجاتك
            sed -i "s|^title = .*|title = My Application|" buildozer.spec
            sed -i "s|^package.name = .*|package.name = myapp|" buildozer.spec
            sed -i "s|^package.domain = .*|package.domain = org.test|" buildozer.spec
            sed -i "s|^version = .*|version = 0.1|" buildozer.spec
            sed -i "s|^requirements = .*|requirements = python3,kivy==2.1.0,pillow,arabic_reshaper,python-bidi,android|" buildozer.spec
            sed -i "s|^android.api = .*|android.api = 33|" buildozer.spec
            sed -i "s|^android.minapi = .*|android.minapi = 21|" buildozer.spec
            sed -i "s|^android.sdk_path = .*|android.sdk_path = /opt/android-sdk|" buildozer.spec
            sed -i "s|^android.archs = .*|android.archs = arm64-v8a,armeabi-v7a|" buildozer.spec
          fi

          # تثبيت python-for-android بطريقة حديثة
          mkdir -p ~/.buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          cd ~/.buildozer/android/platform/python-for-android
          git checkout master
          pip install --use-pep517 -e .

      # الخطوة 8: البناء باستخدام Buildozer
      - name: Build APK with Buildozer
        run: |
          # تنظيف البناء السابق
          buildozer android clean || true

          # البناء مع تسجيل مفصل
          buildozer -v android debug 2>&1 | tee build.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== Build Failed ==="
            cat build.log
            exit 1
          fi

      # الخطوة 9: رفع الملف الناتج
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
          retention-days: 7
