name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # الخطوة 1: استخراج الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد بايثون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # الخطوة 3: تثبيت التبعيات
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-18-jdk \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            python3-pip

          echo "JAVA_HOME=/usr/lib/jvm/java-18-openjdk-amd64" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

          pip install --upgrade pip cython buildozer

      # الخطوة 4: تثبيت Android SDK
      - name: Install Android SDK
        env:
          ANDROID_SDK_ROOT: /opt/android-sdk
        run: |
          # إنشاء مجلد Android SDK
          sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          sudo chown -R $USER:$USER $ANDROID_SDK_ROOT

          # تنزيل أدوات القيادة (Command-Line Tools)
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools

          # نقل المحتويات إلى المجلد المناسب
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          # قبول الرخص
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

          # تثبيت المكونات
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-33" "build-tools;36.0.0"

          # إضافة المسارات إلى البيئة
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      # الخطوة 5: تثبيت Android NDK
      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d /opt
          echo "ANDROIDNDK=/opt/android-ndk-r25b" >> $GITHUB_ENV

      # الخطوة 6: إصلاح مسارات الأدوات
      - name: Fix SDK tools path
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools
          ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin $ANDROID_SDK_ROOT/tools/bin

      # الخطوة 7: التحقق من الأدوات
      - name: Verify Android tools
        run: |
          echo "SDK path: $ANDROID_SDK_ROOT"
          ls -la $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          which sdkmanager
          javac -version

      # الخطوة 8: تخزين مجلدات Buildozer مؤقتًا
      - name: Cache Buildozer directories
        uses: actions/cache@v3
        with:
          path: |
            .buildozer_global
            .buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      # الخطوة 9: البناء باستخدام Buildozer
      - name: Build with Buildozer
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROIDNDK=/opt/android-ndk-r25b
          export ANDROIDAPI=33
          export NDK_API=21
          
          # تنظيف البناء السابق (اختياري)
          buildozer android clean
          
          # بناء التطبيق
          buildozer --verbose android debug

      # الخطوة 10: رفع ملف APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
