name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: /opt/android-sdk
  ANDROID_NDK_HOME: /opt/android-ndk/25.1.8937393
  BUILDDOZER_ANDROID_ACCEPT_LICENSE: yes

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses5 \
            zlib1g-dev \
            python3-pip \
            python3-dev

      - name: Install Cython and build dependencies
        run: |
          # تثبيت Cython عبر pip بدلاً من apt
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.33

      - name: Install Android NDK
        run: |
          sudo mkdir -p /opt/android-ndk
          sudo chown -R $USER:$USER /opt/android-ndk
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d /opt/android-ndk
          mv /opt/android-ndk/android-ndk-r25b /opt/android-ndk/25.1.8937393
          echo "/opt/android-ndk/25.1.8937393" >> $GITHUB_PATH
          echo "ANDROID_NDK_HOME=/opt/android-ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown -R $USER:$USER $ANDROID_SDK_ROOT
          
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-latest
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools-latest $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Install Python build dependencies
        run: |
          pip install buildozer
          pip install kivy==2.1.0 kivymd==1.1.1 pillow arabic_reshaper python-bidi mutagen

      - name: Build with Buildozer
        timeout-minutes: 45
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROIDNDK=$ANDROID_NDK_HOME
          export ANDROIDAPI=33
          
          # تنظيف البناء السابق
          rm -rf .buildozer/android/platform/build-*/
          rm -rf .buildozer/android/app
          
          buildozer --verbose android debug || (find .buildozer -name "*.log" -exec cat {} \; && exit 1)

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk