- name: Setup Buildozer
  run: |
    # إنشاء رابط رمزي لـ tools/bin (اختياري)
    mkdir -p $ANDROID_SDK_ROOT/tools
    ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin $ANDROID_SDK_ROOT/tools/bin

    # التحقق من وجود ملف buildozer.spec
    if [ ! -f buildozer.spec ]; then
      # إنشاء ملف buildozer.spec إذا لم يكن موجودًا
      buildozer init

      # كتابة إعدادات مخصصة لملف buildozer.spec
      cat <<EOF > buildozer.spec
[app]
# (str) عنوان التطبيق
title = My Application

# (str) اسم الحزمة
package.name = myapp

# (str) نطاق الحزمة (مطلوب لتغليف Android/iOS)
package.domain = org.test

# (str) مسار كود المصدر الرئيسي
source.dir = .

# (list) ملفات المصدر للشمول (اتركه فارغًا لشمول جميع الملفات)
source.include_exts = py,png,jpg,kv,atlas

# (str) نسخة التطبيق
version = 0.1

# (list) متطلبات التطبيق
requirements = python3,kivy==2.1.0,pillow,arabic_reshaper,python-bidi,android

# (int) API المستهدف لأنظمة Android
android.api = 33

# (int) الحد الأدنى لـ API يدعمه التطبيق
android.minapi = 21

# (bool) قبول رخص Android SDK تلقائيًا
android.accept_sdk_license = True

# (str) مسار Android SDK
android.sdk_path = /opt/android-sdk

# (list) ориентации المدعومة
orientation = portrait

# (list) معالجات Android المستهدفة
android.archs = arm64-v8a,armeabi-v7a

# (bool) تمكين ميزة النسخ الاحتياطي التلقائي
android.allow_backup = True

[buildozer]
# (int) مستوى السجلات (0 = خطأ فقط، 1 = معلومات، 2 = تصحيح مع إخراج الأوامر)
log_level = 2

# (int) عرض تحذير إذا تم تشغيل Buildozer كجذر (0 = False، 1 = True)
warn_on_root = 1
EOF
    fi
